### ISSUE TITLE
Domain Fronting?

### ISSUE THREAD

**Issue by Viss** [stealth/sshttp#12]
Is it possible to use sshttp with cloudfront or other providers for domain fronting?
It would be pretty rad to have "https traffic flowing to a0.awsstatic.com", that is domain fronted to another front end, like an ec2 or digital ocean image, and have the traffic be ssh.

Because at that point, you could tunnel ssh ports over that link and do c2 and exfil comms over "amazons front end".

**Comment by stealth** [comment]
I expect such providers to sanitize or at least check/verify the TLS/HTTP traffic. Thus, I dont think
that it would be possible to simply forward SSH. You would need to encapsulate SSH inside
HTTPS and untunnel it at the end. Thats not the aim of sshttp. You can use your standard HTTPS
tunnel tools for this.
