### ISSUE TITLE
Problems running sshttp

### ISSUE THREAD

**Issue by jkluch** [stealth/sshttp#4]
I'm trying to run this on a rasp pi.
I downloaded project,
modified nf-setup with
`SSH_PORT=22`
`HTTP_PORT=4433`
 ran `make`
then if I run `./sshttpd -L 443`
I get 
```
sshttpd: Using HTTP_PORT=8080 SSH_PORT=22 and local port=443. Going background.
Using caps/chroot.
NS_Socket::bind_local::bind:Permission denied
```
and if I use sudo I get
```
sshttpd: Using HTTP_PORT=8080 SSH_PORT=22 and local port=443. Going background.
Using caps/chroot.
chroot: No such file or directory
chroot: No such file or directory
```
I also tried using authbind instead of sudo and I get
```
sshttpd: Using HTTP_PORT=8080 SSH_PORT=22 and local port=443. Going background.
Using caps/chroot.
Operation not permitted
```

Anyone able to help with this? Thanks

**Comment by aureq** [comment]
The reason is because to bind to a port < 1024, you must be "root". Please note that it's a feature from the OS rather than a bug in sshttp.
Feel free to give it a try with a higher port so you can see the difference.

**Comment by jkluch** [comment]
>The reason is because to bind to a port < 1024, you must be "root"

Right.  That's why I tried sudo and authbind because they should allow me to use restricted ports.  I've tried random ports above 1024 but I get

```
sshttpd: Using HTTP_PORT=8080 SSH_PORT=22 and local port=5050. Going background.
Using caps/chroot.
Operation not permitted
```
which is similar to what I get when using authbind and port 443.

If I use sudo the output is still the same
```
sshttpd: Using HTTP_PORT=8080 SSH_PORT=22 and local port=5050. Going background.
Using caps/chroot.
chroot: No such file or directory
chroot: No such file or directory
```

**Comment by stealth** [comment]
Yes, you need to run sshttp as root. it will then drop to specified user (default nobody)
and chroot to /var/lib/empty. Either create that directory, or use -R to specify another one.

**Comment by stealth** [comment]
solved I guess
